[theme]
primaryColor="#315A92"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"
font="sans serif"


[server]
port=8501 # change port number. By default streamlit uses 8501 port
#headless=true # This will eliminate automatically open browser

[browser] # This ip and port will show in command prompt
serverAddress = "localhost" # Put your Local IP or Domain Name
serverPort=8501