[theme]
primaryColor="#315A92"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"
font="sans serif"

[browser]
serverAddress = "localhost"

[server]
enableCORS = false
enableXsrfProtection = false


